zeus-transaction-orig:
  api:
    version: 1.0.0
server:
  port: 8085
spring:
  kafka:
    producer:
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
    consumer:
      group-id: zeus-transaction-orig-consumer-group
      enable-auto-commit: true
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring:
          json:
            trusted:
              packages: "*"
    # bootstrap-servers: localhost:9092
  datasource:
    url: jdbc:mysql://localhost:3306/transactionorigdb?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: transactionorigapp
    password: password
    hikari:
      max-lifetime: 600000
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        show_sql: true
        format_sql: true
  flyway:
    user: transactionorigadmin
    password: password
    clean-disabled: false
  profiles:
    active: local, clean
logging:
  file:
    name: logs/local/transactionorig.log
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql: trace


