zeus-transaction-orig:
  api:
    version: 1.0.0
server:
  port: 8085
spring:
  kafka:
    bootstrap-servers: localhost:9092
  datasource:
    url: jdbc:mysql://localhost:3306/transactionorigdb?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: transactionorigapp
    password: password
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        show_sql: true
        format_sql: true
  flyway:
    user: transactionorigadmin
    password: password
  profiles:
    active: local, clean
logging:
  file:
    name: logs/local/transactionorig.log
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql: trace


