openapi: 3.0.1
info:
  title: OpenAPI definition
  version: v0
servers:
- url: http://localhost:8085
  description: Generated server url
paths:
  /api/v1/trans-orig:
    post:
      tags:
      - transaction-origination
      description: Receive the details of the file with all the transactions in the
        file
      operationId: postFileDetails
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/FileDetailDto"
        required: true
      responses:
        "201":
          description: Successfully received the details of the file and started to
            process
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ZeusApiResponse"
  /api/v1/trans-orig/{transactionId}:
    get:
      tags:
      - transaction-origination
      description: Get the details of the transaction by its id
      operationId: getTransactionById
      parameters:
      - name: transactionId
        in: path
        required: true
        schema:
          type: string
      responses:
        "200":
          description: Successfully retrieved the details of the transaction
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ZeusApiResponse"
  /api/v1/trans-orig/delete:
    delete:
      tags:
      - transaction-origination
      description: Delete all data
      operationId: Delete all data
      responses:
        "204":
          description: Data deleted successfully
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ZeusApiResponse"
  /api/v1/trans-orig/delete/{icn}:
    delete:
      tags:
      - transaction-origination
      description: Delete the data for the given ICN
      operationId: cleanUp
      parameters:
      - name: icn
        in: path
        required: true
        schema:
          type: string
      responses:
        "204":
          description: Data for the given ICN successfully deleted
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ZeusApiResponse"
components:
  schemas:
    FileDetailDto:
      type: object
      properties:
        fileDetailSK:
          type: string
          format: uuid
        zeusFileControlNumber:
          type: string
        interchangeControlNumber:
          type: string
        fileName:
          type: string
        fileReceivedDate:
          type: string
          format: date-time
        tradingPartnerId:
          type: string
        senderId:
          type: string
        receiverId:
          type: string
        lineOfBusinessTypeCode:
          type: string
        businessUnitTypeCode:
          type: string
        marketplaceTypeCode:
          type: string
        stateTypeCode:
          type: string
        fileData:
          type: string
        transactionControlNumbers:
          type: array
          items:
            $ref: "#/components/schemas/ZeusTransactionControlNumber"
    PremiumPaymentDto:
      required:
      - enrollmentSpanCode
      - paymentAmount
      - paymentDate
      type: object
      properties:
        enrollmentSpanCode:
          type: string
          description: Enrollment Span Code
          example: IDNTD4VNLJK9VL3
        paymentAmount:
          type: number
          description: Premium Amount being paid
          example: 350.0
        paymentDate:
          type: string
          description: The payment date of the premium span
          format: date
    TestAccountEntityCodes:
      type: object
      properties:
        entityCodes:
          type: object
          additionalProperties:
            type: array
            items:
              type: string
        memberEntityCodes:
          type: array
          items:
            $ref: "#/components/schemas/TestMemberEntityCodes"
    TestMemberEntityCodes:
      type: object
      properties:
        exchangeMemberId:
          type: string
        entityCodes:
          type: object
          additionalProperties:
            type: array
            items:
              type: string
    ZeusTransactionControlNumber:
      type: object
      properties:
        tcn:
          type: string
        ztcn:
          type: string
        accountEntityCodes:
          $ref: "#/components/schemas/TestAccountEntityCodes"
        premiumPayments:
          type: array
          items:
            $ref: "#/components/schemas/PremiumPaymentDto"
    ZeusApiResponse:
      type: object
      properties:
        timestamp:
          type: string
          format: date-time
        statusCode:
          type: integer
          format: int32
        status:
          type: string
          enum:
          - 100 CONTINUE
          - 101 SWITCHING_PROTOCOLS
          - 102 PROCESSING
          - 103 EARLY_HINTS
          - 103 CHECKPOINT
          - 200 OK
          - 201 CREATED
          - 202 ACCEPTED
          - 203 NON_AUTHORITATIVE_INFORMATION
          - 204 NO_CONTENT
          - 205 RESET_CONTENT
          - 206 PARTIAL_CONTENT
          - 207 MULTI_STATUS
          - 208 ALREADY_REPORTED
          - 226 IM_USED
          - 300 MULTIPLE_CHOICES
          - 301 MOVED_PERMANENTLY
          - 302 FOUND
          - 302 MOVED_TEMPORARILY
          - 303 SEE_OTHER
          - 304 NOT_MODIFIED
          - 305 USE_PROXY
          - 307 TEMPORARY_REDIRECT
          - 308 PERMANENT_REDIRECT
          - 400 BAD_REQUEST
          - 401 UNAUTHORIZED
          - 402 PAYMENT_REQUIRED
          - 403 FORBIDDEN
          - 404 NOT_FOUND
          - 405 METHOD_NOT_ALLOWED
          - 406 NOT_ACCEPTABLE
          - 407 PROXY_AUTHENTICATION_REQUIRED
          - 408 REQUEST_TIMEOUT
          - 409 CONFLICT
          - 410 GONE
          - 411 LENGTH_REQUIRED
          - 412 PRECONDITION_FAILED
          - 413 PAYLOAD_TOO_LARGE
          - 413 REQUEST_ENTITY_TOO_LARGE
          - 414 URI_TOO_LONG
          - 414 REQUEST_URI_TOO_LONG
          - 415 UNSUPPORTED_MEDIA_TYPE
          - 416 REQUESTED_RANGE_NOT_SATISFIABLE
          - 417 EXPECTATION_FAILED
          - 418 I_AM_A_TEAPOT
          - 419 INSUFFICIENT_SPACE_ON_RESOURCE
          - 420 METHOD_FAILURE
          - 421 DESTINATION_LOCKED
          - 422 UNPROCESSABLE_ENTITY
          - 423 LOCKED
          - 424 FAILED_DEPENDENCY
          - 425 TOO_EARLY
          - 426 UPGRADE_REQUIRED
          - 428 PRECONDITION_REQUIRED
          - 429 TOO_MANY_REQUESTS
          - 431 REQUEST_HEADER_FIELDS_TOO_LARGE
          - 451 UNAVAILABLE_FOR_LEGAL_REASONS
          - 500 INTERNAL_SERVER_ERROR
          - 501 NOT_IMPLEMENTED
          - 502 BAD_GATEWAY
          - 503 SERVICE_UNAVAILABLE
          - 504 GATEWAY_TIMEOUT
          - 505 HTTP_VERSION_NOT_SUPPORTED
          - 506 VARIANT_ALSO_NEGOTIATES
          - 507 INSUFFICIENT_STORAGE
          - 508 LOOP_DETECTED
          - 509 BANDWIDTH_LIMIT_EXCEEDED
          - 510 NOT_EXTENDED
          - 511 NETWORK_AUTHENTICATION_REQUIRED
        reason:
          type: string
        message:
          type: string
        developerMessage:
          type: string
        response:
          type: object
